# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd80b7ac73b697ea1428a9042b5e47baf345f9bb6cb3eafd205a0df0b586e1b54aa52f284298d264ede56b6d3ce55f03837bed7af9d30c0dc3d4a98975a0d78c

test:
  secret_key_base: 0db5244d22821765f6bfbaa602089088a39f27bb59cd541a588c250d7c364a589108437adf6afc090c081cece85cd0a8df9dbac790074e669f2c76253ff4c273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
